server:
  port: ${PORT:8080}
  address: ${SERVER_ADDRESS:127.0.0.1}
spring:
  application:
    name: parlour-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/parlour;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  flyway:
    enabled: true
  sql:
    init:
      mode: never
management:
  endpoints:
    web:
      exposure:
        include: health,info
---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
