create extension if not exists "pgcrypto";
create type public.app_role as enum ('SUPER_ADMIN','OWNER','MANAGER','RECEPTIONIST','STAFF');
create type public.venue_status as enum ('ACTIVE','INACTIVE');
create type public.resource_status as enum ('AVAILABLE','OCCUPIED','MAINTENANCE','DISABLED');
create type public.booking_status as enum ('SCHEDULED','CONFIRMED','CANCELLED','NO_SHOW','COMPLETED');
create type public.session_status as enum ('ACTIVE','PAUSED','COMPLETED','CANCELLED');
create type public.payment_method as enum ('CASH','UPI','CARD','OTHER');

create table public.venues (id uuid primary key default gen_random_uuid(),name text not null,address text,phone text,email text,timezone text not null default 'Asia/Kolkata',opening_time time not null default '10:00',closing_time time not null default '02:00',currency text not null default 'INR',status venue_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,venue_id uuid references public.venues(id) on delete cascade,name text not null,phone text,role app_role not null,status venue_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check ((role='SUPER_ADMIN' and venue_id is null) or (role <> 'SUPER_ADMIN' and venue_id is not null)));
create table public.customers (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,name text not null,phone text not null,total_visits integer not null default 0 check(total_visits>=0),total_spending numeric(12,2) not null default 0 check(total_spending>=0),last_visit_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(venue_id,phone));
create table public.resource_categories (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,name text not null,description text,status venue_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(venue_id,name));
create table public.resources (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,category_id uuid references public.resource_categories(id),name text not null,description text,status resource_status not null default 'AVAILABLE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(venue_id,name));
create table public.pricing_rules (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,resource_id uuid references public.resources(id) on delete cascade,category_id uuid references public.resource_categories(id) on delete cascade,unit text not null check(unit in ('HOUR','HALF_HOUR','FIXED')),rate numeric(12,2) not null check(rate>=0),fixed_minutes integer,starts_at time,ends_at time,status venue_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((unit='FIXED' and fixed_minutes is not null) or unit<>'FIXED'));
create table public.bookings (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,resource_id uuid not null references public.resources(id),customer_id uuid not null references public.customers(id),created_by uuid references public.profiles(id),start_time timestamptz not null,end_time timestamptz not null,status booking_status not null default 'CONFIRMED',price_estimate numeric(12,2),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_time>start_time));
create table public.sessions (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,resource_id uuid not null references public.resources(id),customer_id uuid not null references public.customers(id),booking_id uuid references public.bookings(id),pricing_rule_id uuid not null references public.pricing_rules(id),started_at timestamptz not null default now(),expected_end_at timestamptz,ended_at timestamptz,status session_status not null default 'ACTIVE',estimated_amount numeric(12,2),final_amount numeric(12,2),created_by uuid references public.profiles(id),ended_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.transactions (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,session_id uuid not null unique references public.sessions(id),subtotal numeric(12,2) not null,discount numeric(12,2) not null default 0,tax numeric(12,2) not null default 0,total numeric(12,2) not null,created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,transaction_id uuid not null references public.transactions(id),amount numeric(12,2) not null check(amount>0),method payment_method not null,status text not null default 'PAID' check(status in ('PENDING','PARTIAL','PAID','REFUNDED')),recorded_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.maintenance_blocks (id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.venues(id) on delete cascade,resource_id uuid not null references public.resources(id),start_time timestamptz not null,end_time timestamptz not null,reason text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),check(end_time>start_time));
create table public.audit_logs (id uuid primary key default gen_random_uuid(),venue_id uuid references public.venues(id) on delete cascade,actor_id uuid references public.profiles(id),action text not null,entity text not null,entity_id uuid,old_value jsonb,new_value jsonb,created_at timestamptz not null default now());
create index on public.customers(venue_id,phone); create index on public.resources(venue_id,status); create index on public.bookings(venue_id,resource_id,start_time,end_time); create index on public.sessions(venue_id,resource_id,status); create index on public.payments(venue_id,created_at);

create function public.current_role() returns app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create function public.current_venue() returns uuid language sql stable security definer set search_path=public as $$select venue_id from public.profiles where id=auth.uid()$$;
create function public.can_access_venue(target uuid) returns boolean language sql stable security definer set search_path=public as $$select current_role()='SUPER_ADMIN' or target=current_venue()$$;
alter table public.venues enable row level security; alter table public.profiles enable row level security; alter table public.customers enable row level security; alter table public.resource_categories enable row level security; alter table public.resources enable row level security; alter table public.pricing_rules enable row level security; alter table public.bookings enable row level security; alter table public.sessions enable row level security; alter table public.transactions enable row level security; alter table public.payments enable row level security; alter table public.maintenance_blocks enable row level security; alter table public.audit_logs enable row level security;
create policy tenant_venues on public.venues for select using(public.can_access_venue(id)); create policy own_profile on public.profiles for select using(id=auth.uid() or public.current_role()='SUPER_ADMIN');
create policy tenant_customers on public.customers for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_categories on public.resource_categories for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_resources on public.resources for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_pricing on public.pricing_rules for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_bookings on public.bookings for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_sessions on public.sessions for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_transactions on public.transactions for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_payments on public.payments for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_maintenance on public.maintenance_blocks for all using(public.can_access_venue(venue_id)) with check(public.can_access_venue(venue_id)); create policy tenant_audit on public.audit_logs for select using(public.can_access_venue(venue_id));
